backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/img" # Media files will be stored in the repo under static/img
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    format: toml-frontmatter
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}/index" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "news"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Other Pages"
    files:
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/call.md"
        label: "Call for Papers"
        name: "call for papers"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/registration.md"
        label: "Registration"
        name: "registration"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/venue.md"
        label: "Venue"
        name: "venue"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/committees.md"
        label: "Committees"
        name: "committees"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/sponsors.md"
        label: "Sponsors"
        name: "sponsors"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}