local_backend: true

backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "content/sponsors" # Media files will be stored in the repo under static/img
public_folder: "" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "announcements" # Used in routes, e.g., /admin/collections/blog
    format: toml-frontmatter
    label: "Announcements" # Used in the UI
    folder: "content/announcements" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: announcements/{{slug}}
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "announcements"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", default: "", format: "YYYY-MM-DD",  date_format: "YYYY-MM-DD", time_format: "false" }
      - {label: "Draft", name: "draft", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "File", name: "file", widget: "file", required: false}
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    format: toml-frontmatter
    label: "About BH7" # Used in the UI
    folder: "content/about" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: about/{{slug}}
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "announcements"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", default: "", format: "YYYY-MM-DD",  date_format: "YYYY-MM-DD", time_format: "false" }
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "File", name: "file", widget: "file", required: false}
  - name: "page"
    format: toml-frontmatter
    label: "Other Pages"
    files:
      - file: "content/_index.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "File", name: "file", widget: "file", required: false}
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        preview_path: contact
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "File", name: "file", widget: "file", required: false}
      - file: "content/call.md"
        label: "Call for Papers"
        name: "call"
        preview_path: call
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "File", name: "file", widget: "file", required: false}
      - file: "content/registration.md"
        label: "Registration"
        name: "registration"
        preview_path: registration
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "File", name: "file", widget: "file", required: false}
      - file: "content/venue.md"
        label: "Venue"
        name: "venue"
        preview_path: venue
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "File", name: "file", widget: "file", required: false}
      - file: "content/committees.md"
        label: "Committees"
        name: "committees"
        preview_path: committees
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "File", name: "file", widget: "file", required: false}
      - file: "content/sponsors/index.md"
        label: "Sponsors"
        name: "sponsors"
        media_folder: "" # Save images in the post's own folder instead of the static folder
        public_folder: ""
        preview_path: sponsors
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "File", name: "file", widget: "file", required: false}
      # - file: "config.toml"
      #   label: "Config Page"
      #   name: "config"
      #   format: "toml"
      #   fields: 
      #   - { label: 'Organizing Committee',
      #       name: 'organizing_committee',
      #       widget: 'object',
      #       fields: [
      #         { label: 'Name', name: 'name', widget: 'string', required: false},
      #         { label: 'Affiliation', name: 'affiliation', widget: 'string', required: false },
      #         { label: 'Link', name: 'link', widget: 'string', required: false},
      #       ],
      #     } 
      #   - { label: 'Scientific Committee',
      #       required: false,
      #       name: 'scientific_committee',
      #       widget: 'object',
      #       fields: [
      #         { label: 'Name', name: 'name', widget: 'string', required: false },
      #         { label: 'Affiliation', name: 'affiliation', widget: 'string', required: false },
      #         { label: 'Link', name: 'link', widget: 'string', required: false },
      #       ],
      #     }
  - name: "program" # Used in routes, e.g., /admin/collections/blog
    format: toml-frontmatter
    label: "Program" # Used in the UI
    folder: "content/program" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}/index" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: program/{{slug}}
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "program"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "File", name: "file", widget: "file", required: false}